### ISSUE TITLE
Portal site issues with manipulating tests and test plans

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#1]
When we started making generators, we found a few issues with adding and editing test plans or tests in the portal.  When you try to add a test plan or test, the Portal site will say that it failed to do so, but if you refresh the page the test plan or test will show up added.  If you try to edit a test plan or test, the whole entire site will go down and crash.  We have seen these issues with the internal portal site, I assume the issues will be in the testing.opendof.org site as well.

**Comment by jwclark** [comment]
Various issues have been fixed. Can you verify whether this is still occurring?

**Comment by amauchley** [comment]
The edit feature on the site doesn't work at all, it no longer crashes the site, but now it just links you forward as if you clicked to just view the test plan or test more fully.  It doesn't let you edit it in any way.

**Comment by amauchley** [comment]
The edit feature on the site doesn't work at all, it no longer crashes the site, but now it just links you forward as if you clicked to just view the test plan or test more fully. It doesn't let you edit it in any way.

**Comment by amauchley** [comment]
You can edit a test plan, but you can't edit a test.  There should be a way for editing a test within the portal when you click on the edit button associated to a test.

**Comment by amauchley** [comment]
Created new bug separately for the test editing issue.  See #170
