### ISSUE TITLE
Portal Site still doesn't run correctly in IE.

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#101]
Though issue #70 fixed rendering the Portal web app in IE, meaning it now shows up the pages, there is still an issue with it functioning properly in IE.  Now that the site renders, another issue occurs, if you try to click on anything, nothing responds.  What happens now is you get this pop-up message from IE:

![capture](https://cloud.githubusercontent.com/assets/13525909/14541066/5097c780-0245-11e6-8101-34912d993555.JPG)

If you tell it to stop the script it will allow you to click something, but it then causes the same error again, so all that you can do is close IE with it complaining it had a problem when trying to run.  Then of course if you restart IE and go to the site, it starts the same issue all over again.

**Comment by amauchley** [comment]
From further investigation, what causes this issue is because of the untested artifacts list is huge for the site.  I'm not for sure why this doesn't cause problems in the other browsers, but for IE since there are ~13000 untested artifacts needing to be listed it doesn't respond while attempting to load all of the list.

What may need to be discussed here as well is if the styling or presentation of this concept is different from just an uber huge list of untested artifact PK numbers.  Some of the thoughts we had were to do an autoscroll like the other pages that have large lists, and/or maybe have a JavaScript slider styling that expands/contracts sections based upon clicking the header. These are just some possible ideas.

**Comment by jwclark** [comment]
Removed untested artifact list from dashboard.
