### ISSUE TITLE
Test Runs that use a network fail to cleanup after result is pushed to database.

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#112]
It seems that any test run that has a network, after failing and putting in the result into the database, the nodes fail to clean up with this log output:

18:08:02.242 DEBUG [RunEntryTask] c.p.dtf.runner.template.BindHandler - BindHandler Bind future.get()[2] called at 2016-06-14 18:08:02
18:08:02.242 DEBUG [RunEntryTask] c.p.dtf.runner.template.BindHandler - BindHandler Bind future.get()[2] returned at 2016-06-14 18:08:02
18:08:02.242 DEBUG [RunEntryTask] c.p.dtf.runner.template.BindHandler - BindHandler bind [2] completes, with attributes of {pslcl.dtf.aws.ec2instance.vpc.tenancy=default, pslcl.dtf.aws.ec2instance.vpc.cidr=10.0.0.0/16, pslcl.dtf.aws.ec2instance.subnet.name=west-1a, pslcl.dtf.aws.ec2instance.subnet.cidr=10.0.0.0/24, pslcl.dtf.aws.ec2instance.sg.max-delay=5000, pslcl.dtf.aws.ec2instance.vpc.max-delay=5000, pslcl.dtf.aws.ec2instance.sg.group-name=dtf, pslcl.dtf.aws.ec2instance.sg.group-id=sg-e916d08d, pslcl.dtf.aws.ec2instance.subnet.vpc-name=null, pslcl.dtf.aws.ec2instance.subnet.size=24, pslcl.dtf.aws.ec2instance.sg.max-retries=17, pslcl.dtf.aws.ec2instance.vpc.max-retries=17, pslcl.dtf.aws.resource.prefix-name=dtf, pslcl.dtf.aws.ec2instance.vpc.name=null}
18:08:02.243 DEBUG [RunEntryTask] c.p.d.r.template.InstancedTemplate - InstancedTemplate runSteps() errors out for templateID �욒�b��j��Ȋ.     �vp����Y5����, templateInstanceID 1
18:08:02.243 DEBUG [RunEntryTask] c.p.d.r.template.TemplateProvider - TemplateProvider releaseTemplate() removes template �욒�b��j��Ȋ. �vp����Y5����, from templateReleaseMap, of templateInstanceID 1
18:08:02.243 DEBUG [RunEntryTask] c.p.d.r.template.TemplateProvider - TemplateProvider removeOneEntry_reusableTemplateList() finds 0 stored reusableITs, for templateHash: �욒�b��j��Ȋ.�vp����Y5����
18:08:02.243 DEBUG [RunEntryTask] c.p.d.r.template.TemplateProvider - TemplateProvider releaseTemplate() destroys template, for templateID �욒�b��j��Ȋ.�vp����Y5����, templateInstanceID 1
18:08:02.243 DEBUG [RunEntryTask] c.p.d.r.template.InstancedTemplate - InstancedTemplate informResourceProviders() about to inform the resource provider system that template �욒�b��j��Ȋ.     �vp����Y5����, templateInstanceID 1 no longer needs its reserved or bound resources
18:08:02.263 DEBUG [RunEntryTask] c.p.d.r.template.InstancedTemplate - InstancedTemplate informResourceProviders()        informed the resource provider system that template �욒�b��j��Ȋ.     �vp����Y5����, templateInstanceID 1 no longer needs its reserved or bound resources
18:08:02.263 DEBUG [RunEntryTask] c.p.dtf.runner.process.RunEntryCore - RunEntryCore testRun errors out, reNum : 3
18:08:02.263 DEBUG [CancelTask] c.p.dtf.runner.process.CancelTask - CancelTask TERMINATES run-cancel checking for reNum 3
PuTTY18:08:02.276 DEBUG [RunEntryTask] c.p.dtf.runner.process.RunEntryCore - RunEntryCore .storeResultAndAckMessageQueue(), for reNum 3, stored to database this result: false
18:08:02.276 WARN  [RunEntryTask] c.p.dtf.runner.process.RunEntryTask - RunEntryTask run() sees exception com.amazonaws.services.sqs.AmazonSQS.deleteMessage(Lcom/amazonaws/services/sqs/model/DeleteMessageRequest;)V
18:08:02.277 DEBUG [RunEntryTask] c.p.dtf.runner.process.RunEntryTask - RunEntryTask run() closes reNum 3
PuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTY18:08:02.363 DEBUG [ReleaseNetworkFuture] c.p.d.r.a.p.n.ReleaseNetworkFuture - Releasing resource start: resourceId: 6
        manager: com.pslcl.dtf.resource.aws.AwsResourcesManager
        provider: com.pslcl.dtf.resource.aws.provider.network.AwsNetworkProvider
        templateId: �욒�b��j��Ȋ.       �vp����Y5����
        templateInstanceId: 1
        runId: 3

18:08:02.363 DEBUG [AwsReleaseFuture] c.p.d.r.a.p.m.MachineReservedResource - MachineReservedResource.setBindFutureCanceled = true
18:08:02.364 INFO  [AwsReleaseFuture] c.p.d.r.a.p.m.AwsMachineProvider - release machine code caught a somewhat unexpected exception during cancel cleanup
java.util.concurrent.ExecutionException: com.pslcl.dtf.core.runner.resource.exception.FatalServerTimeoutException: resourceId: 4
        manager: com.pslcl.dtf.resource.aws.AwsResourcesManager
        provider: com.pslcl.dtf.resource.aws.provider.machine.AwsMachineProvider
        templateId: �욒�b��j��Ȋ.       �vp����Y5����
        templateInstanceId: 1
        runId: 3
message: null-ec2-0x1 stafPing
maxDelay: 5000 maxRetries: 17
totalTime: 1.0216666666666667min

```
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at com.pslcl.dtf.resource.aws.provider.machine.AwsMachineProvider.releasePossiblePendings(Unknown Source)
    at com.pslcl.dtf.resource.aws.provider.machine.AwsMachineProvider.release(Unknown Source)
    at com.pslcl.dtf.resource.aws.AwsResourcesManager$ReleaseFuture.call(Unknown Source)
    at com.pslcl.dtf.resource.aws.AwsResourcesManager$ReleaseFuture.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Caused by: com.pslcl.dtf.core.runner.resource.exception.FatalServerTimeoutException: resourceId: 4
        manager: com.pslcl.dtf.resource.aws.AwsResourcesManager
        provider: com.pslcl.dtf.resource.aws.provider.machine.AwsMachineProvider
        templateId: �욒�b��j��Ȋ.       �vp����Y5����
        templateInstanceId: 1
        runId: 3
message: null-ec2-0x1 stafPing
maxDelay: 5000 maxRetries: 17
totalTime: 1.0216666666666667min

```
    at com.pslcl.dtf.resource.aws.ProgressiveDelay.retry(Unknown Source)
    at com.pslcl.dtf.resource.aws.ProgressiveDelay.retry(Unknown Source)
    at com.pslcl.dtf.resource.aws.instance.machine.MachineInstanceFuture.waitForStaf(Unknown Source)
    at com.pslcl.dtf.resource.aws.instance.machine.MachineInstanceFuture.createInstance(Unknown Source)
    at com.pslcl.dtf.resource.aws.instance.machine.MachineInstanceFuture.call(Unknown Source)
    at com.pslcl.dtf.resource.aws.instance.machine.MachineInstanceFuture.call(Unknown Source)
    ... 4 common frames omitted
```

And then after this error we get into this state of messages:

PuTTYPuTTYPuTTYPuTTYPuTTY18:08:02.590 DEBUG [ReleaseNetworkFuture] c.p.d.r.a.p.n.ReleaseNetworkFuture - Releasing resource complete: resourceId: 6
        manager: com.pslcl.dtf.resource.aws.AwsResourcesManager
        provider: com.pslcl.dtf.resource.aws.provider.network.AwsNetworkProvider
        templateId: �욒�b��j��Ȋ.       �vp����Y5����
        templateInstanceId: 1
        runId: 3

PuTTY18:08:09.054 DEBUG [SessionCallBackSchedulerThread-1] com.pslcl.dtf.resource.aws.Sqs -

18:08:09.054 DEBUG [SessionCallBackSchedulerThread-1] com.pslcl.dtf.resource.aws.Sqs - GetQueueStoreCallback.onMessage() msgID ID:5015ec1b-ee5f-4c33-a811-dbe410f66fac, strQueueStoreNumber 3. Submits to RunnerService to form or reject a test run.
18:08:09.055 DEBUG [SessionCallBackSchedulerThread-1] com.pslcl.dtf.runner.RunnerService - RunnerService.submitQueueStoreNumber() finds reNum 3 has a non-null result already stored. Acking this reNum now.
18:08:09.055 DEBUG [SessionCallBackSchedulerThread-1] com.pslcl.dtf.resource.aws.Sqs - GetQueueStoreCallback.onMessage() msgID ID:5015ec1b-ee5f-4c33-a811-dbe410f66fac, strQueueStoreNumber 3. Drop msg - JMS message rejected by RunnerService
18:08:09.055 WARN  [SessionCallBackSchedulerThread-1] com.pslcl.dtf.resource.aws.Sqs - GetQueueStoreCallback.onMessage() msgID ID:5015ec1b-ee5f-4c33-a811-dbe410f66fac, strQueueStoreNumber 3. Message not acked
18:08:25.563 DEBUG [PslclScheduledExecutor-2] c.p.d.r.a.p.m.AwsMachineProvider -
StalledReleaseTaskStaledRelease timout check
        stalledMap entries:

18:08:39.059 DEBUG [SessionCallBackSchedulerThread-1] com.pslcl.dtf.resource.aws.Sqs -

18:08:39.059 DEBUG [SessionCallBackSchedulerThread-1] com.pslcl.dtf.resource.aws.Sqs - GetQueueStoreCallback.onMessage() msgID ID:5015ec1b-ee5f-4c33-a811-dbe410f66fac, strQueueStoreNumber 3. Submits to RunnerService to form or reject a test run.
18:08:39.059 DEBUG [SessionCallBackSchedulerThread-1] com.pslcl.dtf.runner.RunnerService - RunnerService.submitQueueStoreNumber() finds reNum 3 has a non-null result already stored. Acking this reNum now.
18:08:39.059 DEBUG [SessionCallBackSchedulerThread-1] com.pslcl.dtf.resource.aws.Sqs - GetQueueStoreCallback.onMessage() msgID ID:5015ec1b-ee5f-4c33-a811-dbe410f66fac, strQueueStoreNumber 3. Drop msg - JMS message rejected by RunnerService
18:08:39.059 WARN  [SessionCallBackSchedulerThread-1] com.pslcl.dtf.resource.aws.Sqs - GetQueueStoreCallback.onMessage() msgID ID:5015ec1b-ee5f-4c33-a811-dbe410f66fac, strQueueStoreNumber 3. Message not acked
18:09:09.062 DEBUG [SessionCallBackSchedulerThread-1] com.pslcl.dtf.resource.aws.Sqs –

And these messages than continue non-stop, which I am curious to think that this might be what causes the rate limit exceeded exceptions for the specific region, since there is an SQS message that never finishes.

**Comment by jwclark** [comment]
I am working on a sample network test that will allow us to test this better.

**Comment by jwclark** [comment]
This issue has been resolved.
