### ISSUE TITLE
The runner fails to deploy any modules found in the .dep files

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#113]
I saw this issue with a standalone node test, where it just needed our testing jar, bash script, and the dependant jar to run.  The dependant jar was specified in the .dep file for the bash script, but was never deployed.

Also, I just thought of something, I wonder if the reason why the .dep file isn’t being used is because how the OperationsTest bash script’s artifact name is actually this in the database:

core-java-testing-dof-oal-7.0/bin/OperationsTest

I wonder if the .dep file should be this instead:

core-java-testing-dof-oal-7.0/bin/OperationsTest.dep

**Comment by jwclark** [comment]
The .dep file needs to be placed in the same directory as it's corresponding artifact in order to end up with the same name prefix.
