### ISSUE TITLE
IP addresses are not being resolved/printed out correctly in command line argument execution

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#114]
If a test uses a network and the generator pulls the IP address for the machine to connect to, when it gets used in the actual command line execution, the variable doesn’t seem to be used correctly.  The stderror output in the log showed that our tests failed to parse an argument since it was just a 0, which would have been an invalid argument for our test.  This is what was shown after the “-address” argument: ${ipaddress 0 1}. So, our test to this portion of the string for the address argument “${ipaddress” and then attempted to parse the 0, and failed.  It looks by this case that the ip address was not correctly resolved or printed out to the command line argument strings.

**Comment by jwclark** [comment]
value references are now correctly URL-encoded in the template.

**Comment by jwclark** [comment]
I'm now seeing the URL encoded string: %24%28ip+0+2%29. Ensure that the string is unencoded before checking for the pattern ${...} suggesting that this is a value reference.

**Comment by jwclark** [comment]
False alarm. I had read the wrong line in the log.
