### ISSUE TITLE
Merging functionality may merge a module into more than what is desired depending on versioning

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#120]
The current setup for merging matching is based off of a startsWith() when looking at versions.  This method call was used in order to allow a module to be merged into one or more modules based on the versioning criteria, so for example you could say to merge a module into every version of the target module that starts with 7.  The issue that happens is if you only ever want to merge a specific module into a one specific target module, and the setup for a companies versioning includes patching.  Take this scenario, if you have a testing module that you want merged into only version 7.0, but you have target modules with version 7.0.1, 7.0.2, 7.0.3, etc.  The testing module that you only wanted merged into 7.0 will also unfortunately be merged into any target module that has a version that starts with 7.0.x.  This issue only manifests itself based upon this type of scenario and initial versioning of certain modules, obviously if the initial version of the target module was version 7.0.0, then the merge statement could include that exact same version, and then the testing module would only be merged as desired into version 7.0.0 instead of all 7.0.x versions.  There needs to be a way to allow the merging across many versions, but also to handle this and possibly other scenarios of different versioning setups.  It might work better if regex expressions were used if you wanted a module to be merged into more than one module, or something similar.

**Comment by jwclark** [comment]
Version matching for merges now uses exact matching unless a '*' is provided at the end of the version string. A \* will result in startsWith() comparison.
