### ISSUE TITLE
findDependencies() method fails with exceptions if .dep files include configurations on artifacts

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#122]
If a .dep file has a artifact listed with a specific configuration the findDependencies() method will fail with a MySQL exception since the query is using the wrong column.  In Core.java line 1462, which is in the findDependencies(), the filter for configurations listed in .dep files is using module.configuration instead of artifact.configuration column for the WHERE clause injection.  This needs to be changed to use the artifact.configuration column, and of course this issue only presents it self if you are using configurations.  If you are not, then the string that get's substituted into the select query statement is blank, causing no errors.

**Comment by jwclark** [comment]
Resolved.
