### ISSUE TITLE
Not all created database statements, resultSets, and file iterator(s) are closed in findDependencies()

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#130]
The findDependencies() creates potential many statements and resultSets during its execution of each line from the file iterator.  These statements become maintained across the execution and even though they may no longer be valid are retained, this in turns uses up much of the JVM's allocated memory since GC doesn't release them.  All resultSets and statements should be closed once they are no longer needed.  The final statement does do a close, but it only closes the most recently used statement/resultSet or the one being used when an exception happened.  Also the iterator that is used for the fileReader should also be closed and not left open.

**Comment by jwclark** [comment]
These are now closed.
