### ISSUE TITLE
Feature Request: Add S3 containment of console output from ran test instances

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#137]
Currently all test output is printed into the dtfrunner.log, it would be nice to have the stdout/stderr outputs and any other files in the sandbox directory on a particular machine and test run to be copied into a directory in S3.  This would allow the ability to link a failed result to actual historical output from within the portal for easy retrieval.  Also for any other engineers helping to debug failed tests would also have a way to download the required output and files to run the given test run. The S3 directories/files would need to have an expiration that they would then be deleted, so that only a certain amount of runs are kept historically at a time to not use up huge amounts of storage at a time.

**Comment by jwclark** [comment]
Logs should also be stored from 'start' machines.

**Comment by amauchley** [comment]
After having ran multiple tests at the same time, we ran into various STAF related failures with creating the logs directory that is used for moving the stdout/stderr logs to S3.  It would be better to not fail a test execution just because the logs directory fails to be created by STAF during initialization of a test.  It isn't that big of a deal if a test fails to create the logs directory, but is still able to run.  In my opinion, I think most people would prefer the test execution to still happen whether or not the logs directory is able to be created on the node running a test.  Worse case scenario a test fails without any logs being able to be stored on S3, and a user has to re-run the test.

**Comment by Chad-Adams** [comment]
s3 logging commands were being attempted for all staf commands being issued (deploy, config, run, start, delete).  This was reduced to only run.  There is no other way to disassociate the execution from the logging and thus allow for logging failure to not fail the test.
