### ISSUE TITLE
unlimited amount of machines were created when a huge amount of tests were queued.

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#139]
I only saw this issue since I queued up a huge test-id that had many test instances.  Even though in my dtf.properties file I had t2.micro instances limited to 20, t2.small - 10, m3.medium -10, and m3.large to 5 instances.  The runner created over 95 t2.micro machines when trying to handle all the queued tests.  I think that this configuration should have limited the amount of machines allocated to just the 45 requested, but it appears to not do so.  The runner should limit how many machines are created in AWS and as soon as those resources are available that the other tests should be able to use them again.  There also may be an issue with it having allocated so many machines in AWS due to the runner thinking that the tests needed different types of machines/ami's and that the currently allocated ones weren't correct.  Though I struggle in believing that since most of our tests use the exact same linux machine/ami.

**Comment by amauchley** [comment]
I've also noticed that sometimes it appears as if there were a lot of machines made, but what really happened was something went wrong with the cleanup of the machine resource and the node isn't terminated or put into a correct idle state.  It's as if the machine can't be communicated too anymore by the dtfrunner service.  So instead of ceasing the rest of the test executions the dtfrunner instantiates more needed machines, since to him the resource is dead.  Generally what happens in this sense is the machine is left up, the test run id is removed and the security group as well, but the machine remains up.

**Comment by Chad-Adams** [comment]
Found a solid issue which was fixed
