### ISSUE TITLE
No way provided to configure generator cron job from not running automatically

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#143]
The current configuration in config.js for the portal only provides a way for scheduling the cron job.  There should be a way for not having the cron job run at all, thereby allowing any test generation to happen only when a user goes in and executes dtfexec. This in turn frees up resources that have been taken for test generators when it should be used for the runner.  Having the cron job run for small groups that may only have a few tests that need to be ran with not that many templates being created, works great.  But if you have a use case where there are many generators that need to be run and have a lot of templates being created, the generation is time consuming and resource consuming, especially on the databases' cpu.  There should be a way to configure the portal to not run the cron job at all, and thereby grant the user of the framework the sole responsibility to decide when its appropriate to have the generators use up resources and when to give them all to the runner.

**Comment by jwclark** [comment]
Portal config now allows disabling generators on synchronize, as well as disabling synchronize all together.
