### ISSUE TITLE
Feature Request: Overall revamp of Report generation and pages

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#146]
After some discussion it was decided that the concepts of what is a report, and what should be included in certain reports needs to be reviewed and decided more thoroughly.  There is many cases where report generation takes a long time, especially for exporting the report to PDF (it even sometimes crashes when trying to do so).  Also some discussion was put on possibly paginating the report pages so that not so many are queried at a time.  There is a substantial bottleneck when it comes to retrieving reports for modules with thousands of tests, and for test plans/tests that have many test/test instances.  Another recommendation was to create a failed test report that would list the test name and test instance ids, so that it would be quicker for QA staff to locate failures for evaluation. As tests passed or were linked to known bugs they would be removed off of the list.

**Comment by jwclark** [comment]
Individual test instances information has been removed from reports. A list of failed tests has been added.
