### ISSUE TITLE
.dep files are duplicating artifact deployments in templates

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#149]
[dtfrunner.tar.gz](https://github.com/PSLCL/testing-framework/files/620641/dtfrunner.tar.gz)
When looking at the log for the runner (above), I noticed that various artifacts were being deployed multiple times on the same machine using the same artifact file.  In this case for the given tests it should have only deployed the artifact once on that machine.  This only happens with dependent artifacts coming from .dep files. This in turn later causes the 'mv' command on that artifact to fail for STAF, which overall fails the test run.

**Comment by amauchley** [comment]
Though certain fixes have been applied, I'm still seeing duplicate entries in generated tests occasionally.  I don't know if this is potentially caused by threading issues, or memory issues, etc.

**Comment by jwclark** [comment]
From #166:

19:17:06.179 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 13, for step: 1 deploy 0 lib/testing-dof-oal-7.0.2.jar.dep 067599829562CC1F0A2D061118CF607DF51E51AEB564F732F5368316696C7C51
19:17:06.179 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 14, for step: 1 deploy 0 lib/testing-dof-oal-7.0.2.jar.dep

**Comment by jwclark** [comment]
Check for duplicates using artifact name instead of .equals.

**Comment by jwclark** [comment]
Duplicates still reporting. artifact.getName() includes module, but the template uses artifact.getTargetFilePath(), which generally does not and may be another cause of duplicates if artifacts from different modules but similar names are somehow added.

Duplicate files wit hthe same 'getTargetFilePath()' should not be added to a template. If such duplicates are found and artifactA.equals(artifactB) resolves to false, then a warning should likely be logged as this may suggest that there is an error in the generator or .dep files.
