### ISSUE TITLE
Dashboard fails to load up the number of untested artifacts

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#153]
The dashboard page has a box that includes the number of untested artifacts, it now is apparent that when there are a larger number of artifacts that aren't tested the page fails to retrieve this number and leaves the box empty.  Here is the console output from Chrome:

[chrome_console_log.txt](https://github.com/PSLCL/testing-framework/files/632277/chrome_console_log.txt)

**Comment by jwclark** [comment]
Untested module count now displayed instead of untested artifacts.
