### ISSUE TITLE
wget used by deploy may take a long time to report fail

### ISSUE THREAD

**Issue by jwclark** [PSLCL/testing-framework#160]
wget has a long timeout(~2 minutes default) and defaults to a retry count of 20. If there is some misconfiguration, or other issue causing failure, this may result in a very long period before failure is detected. Reduce the number of retries used by wget.

**Comment by Chad-Adams** [comment]
fixed for linux which defaults to 20 retries.  However windows does not have this retry issue.  It uses powershell's 'invoke-webrequest' which does not support retries.
