### ISSUE TITLE
CLI support for running tests for only a specific module

### ISSUE THREAD

**Issue by jwclark** [PSLCL/testing-framework#162]
'bin/dtfexec run --test <id>' is currently used to queue up a test run for each test instance of the specified test. In the case of large tests, this may result in a very large number of test runs. Allow the user to specify a module so that only test instances with a dependency on that module are queued.

e.g.

bin/dtfexec run --test <test-id> --module <module-id>

The module option should only be supported if '--test' is also specified.

**Comment by clintjones** [comment]
To clarify, this is accepted (multiple test numbers against 1 module number)::
bin/dtfexec run --test 11 17 --module 177 //restrict tests 11 and 17 to module 177

Not accepted is any attempt to specify multiple module numbers.
