### ISSUE TITLE
Log directory creation failure causes the test to fail

### ISSUE THREAD

**Issue by jwclark** [PSLCL/testing-framework#164]
If STAF sees a failure to create the logging directory, the test fails.

Failure to capture logs is concerning(#165), but doesn't necessarily mean that the test should be failed. When this error occurs, allow the test to continue running.

**Comment by timpanogos** [comment]
There is not  a way to separate the execution from creation of the logging folder and stdout/stderror.log files.
bug #165 simply needs to be fixed.

http://staf.sourceforge.net/current/STAFUG.htm#HDRPROCSRV see START STDOUT STDERR

"STDOUT specifies the name of the file to which standard output will be redirected. If the file already exists, it will be replaced. If the directory path specified for the file does not exist, it will be created. This option will resolve variables using the IGNOREERRORS option."
