### ISSUE TITLE
null pointers occurring during execution of generators

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#171]
Some of the OpenDOF generators are logging that there were null pointers occurring during their execution, but there isn't much else to go on from the log outputs.  It would be good to give more information as to where the null pointer is occurring and in what generator.  If possible it would be good to also show the parameters going into the generator as well.

Here is what the current logging output states:

02:43:12.106 [main] WARN com.pslcl.dtf.core.generator.template.TestInstance$Action$ActionSorter - TestInstance.Action.ActionSorter.compare() catches Exception but must swallow it, msg: java.lang.NullPointerException
02:43:12.177 [main] ERROR com.pslcl.dtf.core.generator.resource.Machine$ProgramAction - <internal> Machine.ProgramAction.getCommand(Template) exits after catching exception, msg: java.lang.NullPointerException

**Comment by jwclark** [comment]
Edited to just be a bug to fix null pointers. If 'null' values are being passed into the public Generator API where null is not expected, then we should be throwing IllegalArgumentException immediately. 

If the Generator code simply has bugs that are causing NullPointerException, then those bugs should be fixed.

**Comment by clintjones** [comment]
fixed. Beyond the commit log message, also added specific null checks to the specific failed-cases expressed in this issue report.
