### ISSUE TITLE
Connection pool closed after null pointer exceptions incurred during test runs

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#172]
After various tests runs null pointer exceptions occurred for any subsequent test run and then eventually the dtfrunner service shutdown the connection pool.  I've attached the log below for the error.
[dtfrunner.log.2017-10-09.log](https://github.com/PSLCL/testing-framework/files/1373134/dtfrunner.log.2017-10-09.log)

**Comment by jwclark** [comment]
Queue shouldn't be initialized until after service starts.
