### ISSUE TITLE
AWS Network to no-op

### ISSUE THREAD

**Issue by jwclark** [PSLCL/testing-framework#177]
In AWS, creating/editing/deleting security group requests are being rate limited. 

Current requirements for Networks  is to simply support communication between test instance machines. This can be supported using the configured security group that is used to allow traffic between the test runner and test instance machines.

Bind network and connect operations should be no-ops, only returning the ip address of the machine with the Cable object.

**Comment by Chad-Adams** [comment]
Unique security groups for individual networks has been disabled
