### ISSUE TITLE
Terminated instances not removed from stalledRelease map

### ISSUE THREAD

**Issue by jwclark** [PSLCL/testing-framework#183]
Machine instances terminated due to cleanup errors, such as in issue #182, don't appear to be removed from AWSMachineProvider.stalledRelease map.

**Comment by jwclark** [comment]
I see the following log, where instances that have been previously terminated are still checked for their timeout:

6:55:14.131 DEBUG [PslclScheduledExecutor-1] c.p.d.r.a.p.m.AwsMachineProvider - 
StalledReleaseTaskStaledRelease timout check
	stalledMap entries:
		configuredTimeout: 60
		delta: 128
		timeout: 178
		still in limit
		AwsMachineInstance
			sanitizing: false
			destroyed: true
			taken: true
			instantiationTime:10/25/17 2:46 PM
			MachineReservedResource:
				
resourceId: 4
					manager: com.pslcl.dtf.resource.aws.AwsResourcesManager
					provider: com.pslcl.dtf.resource.aws.provider.machine.AwsMachineProvider
					templateId: 0x71efbfbd5b6c4d3defbfbd140255efbfbd5c3eefbfbd66efbfbdefbfbd4fefbf
					templateInstanceId: 1
					runId: 2
				instanceType = t2.micro
				imageId = ami-d8f3ffce
				bindFutureCanceled = true
				reusable = true
			configuredTimeout: 60
			delta: 114
			timeout: 118
			still in limit
			AwsMachineInstance
				sanitizing: false
				destroyed: true
				taken: true
				instantiationTime:10/25/17 3:00 PM
				MachineReservedResource:
					
resourceId: 5
						manager: com.pslcl.dtf.resource.aws.AwsResourcesManager
						provider: com.pslcl.dtf.resource.aws.provider.machine.AwsMachineProvider
						templateId: 0x71efbfbd5b6c4d3defbfbd140255efbfbd5c3eefbfbd66efbfbdefbfbd4fefbf
						templateInstanceId: 1
						runId: 2
					instanceType = t2.micro
					imageId = ami-90ecb3eb
					bindFutureCanceled = true
					reusable = true
				configuredTimeout: 60
				delta: 6
				timeout: 58
				still in limit
				AwsMachineInstance
					sanitizing: false
					destroyed: true
					taken: true
					instantiationTime:10/25/17 4:48 PM
					MachineReservedResource:
						
resourceId: 13
							manager: com.pslcl.dtf.resource.aws.AwsResourcesManager
							provider: com.pslcl.dtf.resource.aws.provider.machine.AwsMachineProvider
							templateId: 0x80eefbfbd34775671efbfbd146e5aefbfbd20efbfbdefbfbdefbfbdefbfbdef
							templateInstanceId: 4
							runId: 5
						instanceType = t2.micro
						imageId = ami-d8f3ffce
						bindFutureCanceled = true
						reusable = true
					configuredTimeout: 60
					delta: 6
					timeout: 58
					still in limit
					AwsMachineInstance
						sanitizing: false
						destroyed: true
						taken: true
						instantiationTime:10/25/17 4:48 PM
						MachineReservedResource:
							
resourceId: 14
								manager: com.pslcl.dtf.resource.aws.AwsResourcesManager
								provider: com.pslcl.dtf.resource.aws.provider.machine.AwsMachineProvider
								templateId: 0x80eefbfbd34775671efbfbd146e5aefbfbd20efbfbdefbfbdefbfbdefbfbdef
								templateInstanceId: 4
								runId: 5
							instanceType = t2.micro
							imageId = ami-d8f3ffce
							bindFutureCanceled = true
							reusable = true

**Comment by Chad-Adams** [comment]
None of the reuse/cleanup code has had any testing done against it.  There are several fairly involved use cases which have been coded in theory but have only had the simplest of test code manually attempting to cause code path execution to happen.

There is a strong push for some kind of unit testing, and yet these errors and code are very complex system level issues.  It seems we just need to write some comprehensive testing of this system, which is not a trivial design/time/engineering effort.  I really don't know how to proceed at this time.

**Comment by jwclark** [comment]
Narrowing scope of issue.

**Comment by Chad-Adams** [comment]
moved removal of stalledRelease resources to the deleteInstance method
