### ISSUE TITLE
QA Portal dashboard displays a historical rather than current Artifacts number

### ISSUE THREAD

**Issue by clintjones** [PSLCL/testing-framework#2]
After an Artifact number is reported by QA Portal, it will display that number even after those artifacts are removed from the test framework database. Rebooting the MySQL Server or restarting the QA Portal app does not restore the Artifact count to 0. It may be that this Artifact count is acting as a historical maximum value.

**Comment by jwclark** [comment]
Various issues have been fixed. Can you verify whether this is still occurring?

**Comment by amauchley** [comment]
I haven't seen this issue anymore, it appears to be resolved.
