### ISSUE TITLE
Generator should generate steps according to new rules

### ISSUE THREAD

**Issue by clintjones** [PSLCL/testing-framework#20]
com.pslcl.dtf.core.generator generates complete test information and fills most tables of the dtf database, to match. It fills steps in table template according to rules from an original technical specification. The dtf project has migrated since then, and follows documentation in testing-framework/docs/design. From templates.md and template_commands.md, these things have changed:

-include steps must now be first (and do not begin with the newly specified setID number)
-all other steps fit into sets, and use a leading setID that starts at 0; on change, setID increases by 1
-bind steps use resource name instead of a resource hash
-deploy steps no longer supply component name

**Comment by clintjones** [comment]
-program steps (configure, start, run) now specify a program name to run, rather than an artifact-name and artifact-hash. The program name could be something like an ordinary linux command, or it could be the name of an executable program that the generator had previously deployed to the machine, using the deploy step.

**Comment by jwclark** [comment]
The generator has been updated to follow the new template command rules.
