### ISSUE TITLE
Bind a Person Resource

### ISSUE THREAD

**Issue by jwclark** [PSLCL/testing-framework#23]
Allow testers to write generators which bind a person resource.
- [x] Runner must parse 'bind person' template commands
- [x] Runner must bind a Person Resource through Resource Provider API calls
- [x] AWS Resource Provider must allow Runner to check availability and reserve Person Resource
- [x] AWS Resource Provider must allow Runner to bind and release Person Resource

**Comment by Chad-Adams** [comment]
aws person provider reserve/bind - rock-n-roll
