### ISSUE TITLE
Bind a Machine Resource

### ISSUE THREAD

**Issue by jwclark** [PSLCL/testing-framework#24]
Allow testers to write generators which bind a machine resource.
- [x] Runner must parse 'bind machine' template commands
- [x] Runner must bind a Machine Resource through Resource Provider API calls
- [x] AWS Resource Provider must allow Runner to check availability and reserve Machine Resource
- [x] AWS Resource Provider must allow Runner to bind and release Machine Resource

**Comment by Chad-Adams** [comment]
Bind-a-Machine branch has aws checkoffs in it.
