### ISSUE TITLE
Bind a Network Resource

### ISSUE THREAD

**Issue by jwclark** [PSLCL/testing-framework#25]
Allow testers to write generators which bind a network resource.
- [x] Runner must parse 'bind network' template commands
- [x] Runner must bind a Network Resource through Resource Provider API calls
- [x] AWS Resource Provider must allow Runner to check availability and reserve Network Resource
- [x] AWS Resource Provider must allow Runner to bind and release Network Resource

**Comment by Chad-Adams** [comment]
AWS checkoffs In Bind-a-Machine Branch
