### ISSUE TITLE
Support Value References

### ISSUE THREAD

**Issue by jwclark** [PSLCL/testing-framework#30]
Allow testers to write generators which specify [value references](https://github.com/PSLCL/testing-framework/blob/AwsProvider/docs/design/value_references.md) so that IP Addresses and Attribute Values can be referenced which are not known until execution time.
- [x] Generator supports value references in templates
- [x] Test Runner parses value references and gets value
- [x] dtf-aws-attr declares all possible AWS name's and their defaults
- [x] dtf-aws-resource supports all possible AWS name/value pair defaults and test-script overrides

**Comment by clintjones** [comment]
ip substitution ValueReference now implementedl

**Comment by clintjones** [comment]
dtf-runner now supports ValueReference attribute substitution.
