### ISSUE TITLE
dtf-runner inspect step needs to work with instructions only, with 0 artifacts to inspect

### ISSUE THREAD

**Issue by clintjones** [PSLCL/testing-framework#59]
Right now it requires at least one artifact to be included as an attachment. 0 artifacts, other than the email content itself, is allowed.

**Comment by ghost** [comment]
That makes no sense. The email content itself is an artifact.

**Comment by jwclark** [comment]
It should read 'attachments'. The issue is that if no artifacts are specified, other than the email content, there is an error.

**Comment by clintjones** [comment]
Fixed
