### ISSUE TITLE
Duplicate run tasks in test runner service

### ISSUE THREAD

**Issue by jwclark** [PSLCL/testing-framework#68]
Some test runner tasks are occasionally duplicated for a single test run. The test run is 'opened' twice. Two machine instances are reserved/bound instead of one. Two 'checkRunCancel' tasks are created.

23:25:09.230 DEBUG [SessionCallBackSchedulerThread-1] com.pslcl.dtf.resource.aws.Sqs - GetQueueStoreCallback.onMessage() msgID ID:464aa487-ac66-4105-9e1f-b1781fdb9224, strQueueStoreNumber 24. Submits to RunnerService to form or reject a test run.
23:25:09.231 DEBUG [SessionCallBackSchedulerThread-1] com.pslcl.dtf.runner.RunnerService - RunnerService.submitQueueStoreNumber() submits reNum 24 for testRun processing. 
23:25:09.237 DEBUG [SessionCallBackSchedulerThread-1] c.p.dtf.runner.process.RunEntryCore - RunEntryCore <internal> loadRunEntryData() loads data from run-template matched records for reNum 24, pk_template 1
23:25:09.245 DEBUG [PslclBlockingExecutor-20] c.p.dtf.runner.process.RunEntryTask - RunEntryTask run() opens reNum 24
23:25:09.261 DEBUG [PslclBlockingExecutor-20] c.p.dtf.runner.process.RunEntryCore - RunEntryCore <internal> loadRunEntryData() loads data from run-template matched records for reNum 24, pk_template 1
23:25:09.269 DEBUG [PslclBlockingExecutor-20] c.p.dtf.runner.process.RunEntryTask - RunEntryTask run() ran Action INITIALIZE for reNum 24, finds next action INITIALIZE
23:25:09.269 DEBUG [PslclBlockingExecutor-21] c.p.dtf.runner.process.RunEntryTask - RunEntryTask run() opens reNum 24
23:25:09.270 DEBUG [PslclBlockingExecutor-21] c.p.dtf.runner.process.RunEntryTask - RunEntryTask run() ran Action ANALYZE for reNum 24, finds next action DO

...

23:25:18.541 DEBUG [PslclBlockingExecutor-27] c.p.dtf.runner.process.RunEntryCore - RunEntryCore .checkRunCancel() called for reNum 24, finds test run running
23:25:18.546 DEBUG [PslclBlockingExecutor-29] c.p.dtf.runner.process.RunEntryCore - RunEntryCore .checkRunCancel() called for reNum 24, finds test run running

**Comment by clintjones** [comment]
Fixed by requiring runEntry state to change before acting.
