### ISSUE TITLE
Ant build is missing complete clean rule

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#73]
The Ant build.xml for the platform needs a complete clean rule that removes the .cache directory files so that if a rebuild of the platform is done using the same version number it will actually build the jars afresh.

**Comment by jwclark** [comment]
Ivy resolvers and caches can be managed using ivysettings.xml. For example, the testing-framework/platform/ivysettings-example.xml filysystem resolver can be changed to have the following attribute: changingPattern="*". This will cause the lastmodified date to be checked and update the cache if changed.
