### ISSUE TITLE
Javadocs for platform modules are fraught with errors

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#75]
The Javadocs for many of the platform modules have numerous errors and need to be fixed.  When you run the 'ant' command as instructed in the README.md file for building the platform, numerous javadoc errors are pummeled in the console output.  Many of the errors in different java class files are the exact same issue spread across multiple files.  To name a few: 
- bad use of '>'
- @param tag issue
- unexpected end tag </p>
- element not close <code> 
- unknown tag @note

**Comment by Chad-Adams** [comment]
I've done a pass on the various resources and should have mine fixed.  Fixes done in the Test-Runner-Development branch.

**Comment by clintjones** [comment]
Fixed and pushed to the Test-Runner-Development branch.
