### ISSUE TITLE
Various typos in markdown files under the docs/design, platform, portal directory

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#81]
There are various typos in some of the markdown files included in the docs/design/, platform/, and portal/ directories.  Here is a list of the markdown file and its typo:
- Portal README.md; "Running Server" section's introduction paragraph, "differ" needs to be "differs".
- Platform README.md; The "Notes" for both AWS IAM Policies do not render the "<queue-arn>" and "<dtf-system-id>" replacement tags correctly.  The IAM policies render them correctly, but in the note section all that shows up is a '\' where it should be '<queue-arn>' or '<dtf-system-id>'.
- Platform README.md; The "Windows Sysprep" section point 1, states "Bring up a remote desktop client to the EC2 image establish in the above..." should have "establish" be changed to "established" 
- core_platform.md (docs/design); "A Developer Connects a Machine to a Network" section, states "A Test Generator developer Requests That a machine Resource be Attached to a network resource..." should be written as "A Test Generator developer requests that a machine Resource be attached to a network resource..."

**Comment by jwclark** [comment]
Github correctly renders the <queue-arn> and <dtf-system-id> under the Note sections.
