### ISSUE TITLE
Export to PDF option from reports doesn't work

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#88]
The Export to PDF button from any type of report doesn't seem do anything.  When you click on the export button nothing appears to happen, there isn't even a processing spinning wheel showing up, it appears to be just a button with now code functionality behind. When further investigating the button's code click, it shows that the click is supposed to be executing exportReport(), but there isn't anything else throughout the site's code that declares/defines what that method is.

**Comment by amauchley** [comment]
The export to pdf button only works on module reports, but even when you do click this for a module report that has tests plans/tests, the pdf report is empty except for the company logo and copyright.

**Comment by jwclark** [comment]
Fixed export to PDF from module report screen. Removed non-working export from test plan report.

**Comment by amauchley** [comment]
The non-working export from a test report still needs to be removed.
