### ISSUE TITLE
machine attributes on generator are forced to be the same in dtf.properties file

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#96]
If the dtf.properties file lists more attributes for certain machine images and the generators only request a machine with one of those attributes, than the execution of finding the image when starting a test will fail.

Take for example, you have in your dtf.properties file an ami that has an attribute for the OS linux, JRE, and Platform.  If you generator only requests a machine that has an OS of linux, when you try to execute the test instance it will fail to find any images that match what is requested.  So basically whatever is listed in the dtf.properties file for the attributes on a machine, than the generators need to add/request the same ones exactly to get it to work.

**Comment by Chad-Adams** [comment]
For better or worst, the "pslcl.dtf.resource.machine.image-id" value is used if no parameters are specified from the test script.  In the case of handling image selection parameters from the test script the "pslcl.dtf.resource.machine.image.config#" key/values are used to specify the combinations of test script name/value pairs that will select the given image-id.  Consider the following example:

pslcl.dtf.resource.machine.image.config0=ami-315b7e5b java=java8
pslcl.dtf.resource.machine.image.config1=ami-315b7e5b architecture=x86_64 java=java8
pslcl.dtf.resource.machine.image.config2=ami-315b7e5b architecture=x86_64 pslcl.dtf.resource.machine.os=linux java=java8
pslcl.dtf.resource.machine.image.config3=ami-c2022ca8 architecture=x86_64 pslcl.dtf.resource.machine.os=windows java=java8  

I also noted that you were using "jre=1.8" in your properties file, which I believe should be "java=1.8" in this brave new world.

if the test script only specified java=java8, the config0's ami will be selected.

I'll leave this issue open until we determine that some new configuration and test.script modifications are working to your satisfaction

**Comment by Chad-Adams** [comment]
woops, dang we are good, the code currently grabs all well known keys and isolates them from any "custom keys" thus my above comment about java=1.8 verses jre=1.8, or any other custom keys you want to map up will be as the test script describes them as compared against the configuration mappings.

**Comment by jwclark** [comment]
The intended use case is that you would only need to specify config2 and config3 in the given example. config0 and config1 are redundant to config2 because they have a strict subset of the attributes specified by config2. 

In other words, for config2 to be a match, the test should not have to specify all configured attributes. The test should be able to specify some subset of those attributes. For example, specifying only the attribute 'java=java8' would be a match for config2, so config0 here is redundant.

**Comment by Chad-Adams** [comment]
Comparison of mapped configurations to test script parameters is now based on the test script parameters being a subset of the properties file configurations
